# Generated by Django 4.0 on 2021-12-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editapp', '0003_department_alter_student_name_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.IntegerField()),
                ('stud_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='st')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dep', models.CharField(max_length=20)),
            ],
        ),
    ]
