# Generated by Django 4.0 on 2021-12-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editapp', '0004_stud_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='stud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
