# Generated by Django 4.0 on 2021-12-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editapp', '0005_teacher_stud_teacher_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('teacher', models.BooleanField(default=False)),
                ('stud', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='stud',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher',
        ),
    ]
