# Generated by Django 4.0 on 2021-12-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.product')),
            ],
        ),
    ]
